# This file was generated by GoReleaser. DO NOT EDIT.
cask "gobrewtest" do
  desc "A completely useless binary; used for testing purposes"
  homepage "https://github.com/dhth/gobrewtest"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gobrewtest"

  on_macos do
    on_intel do
      url "https://github.com/dhth/gobrewtest/releases/download/v0.3.0/gobrewtest_0.3.0_darwin_amd64.tar.gz"
      sha256 "c78451afcd0d067abccccdc70ae5b851c3cc6175cb99963a62247866213fe950"
    end
    on_arm do
      url "https://github.com/dhth/gobrewtest/releases/download/v0.3.0/gobrewtest_0.3.0_darwin_arm64.tar.gz"
      sha256 "a32ae237c7a5db6fe27ef11cf409d298d15ebc7688ad8e77e48f6bd21dc50c99"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dhth/gobrewtest/releases/download/v0.3.0/gobrewtest_0.3.0_linux_amd64.tar.gz"
      sha256 "05aa4e328775e1756b99915c9341b4613892acb938ace72aff1e2f6e35f9ba51"
    end
    on_arm do
      url "https://github.com/dhth/gobrewtest/releases/download/v0.3.0/gobrewtest_0.3.0_linux_arm64.tar.gz"
      sha256 "e7161508e4cfa863dbe141ea4fa682f255bcafd83778d697ac3ed6cfdcdf6d3d"
    end
  end

  conflicts_with formula: [
      "gobrewtest",
    ]

  # No zap stanza required
end
