# This file was generated by GoReleaser. DO NOT EDIT.
cask "gobrewtest" do
  version "0.4.2"

  on_macos do
    on_intel do
      sha256 "3adca9dc819ebe609b950b3830df8e3f181a0f0d7e5c4003d43967a45ea439c1"
      url "https://github.com/dhth/gobrewtest/releases/download/v#{version}/gobrewtest_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b61a60fa8836b786571305c9f39c90ba904469f87c5d735ec984537311e2ef95"
      url "https://github.com/dhth/gobrewtest/releases/download/v#{version}/gobrewtest_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4d5a046abb71fbe11b04a738edc9b462dd60b16ec728b3f26c5f50d8d97a1de8"
      url "https://github.com/dhth/gobrewtest/releases/download/v#{version}/gobrewtest_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c49ec4ad27f3c311a43ab9735590432618fe48d38c3c2216604644ffa7f291e7"
      url "https://github.com/dhth/gobrewtest/releases/download/v#{version}/gobrewtest_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gobrewtest"
  desc "A completely useless binary; used for testing purposes"
  homepage "https://github.com/dhth/gobrewtest"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gobrewtest"

  # No zap stanza required

end
