# This file was generated by GoReleaser. DO NOT EDIT.
cask "tflens" do
  name "tflens"
  desc "tflens offers tiny utilities for terraform/opentofu/terragrunt codebases"
  homepage "https://github.com/dhth/tflens"
  version "0.1.0-alpha.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tflens"

  on_macos do
    on_intel do
      url "https://github.com/dhth/tflens/releases/download/v#{version}/tflens_#{version}_darwin_amd64.tar.gz"
      sha256 "6a7f0a86785c107c89d950ebfcbc90fa3aa7aed4a2c2b9f662b2b0fa6ac4d22c"
    end
    on_arm do
      url "https://github.com/dhth/tflens/releases/download/v#{version}/tflens_#{version}_darwin_arm64.tar.gz"
      sha256 "81ebe2cc992f14f01b68204601f2253c7fe69df30c407773de31f63ff6b7b928"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dhth/tflens/releases/download/v#{version}/tflens_#{version}_linux_amd64.tar.gz"
      sha256 "80e3202e573470fa80e7ab62a29bb6ac0d3dd4710b61d80e1afbd81eb848cd0b"
    end
    on_arm do
      url "https://github.com/dhth/tflens/releases/download/v#{version}/tflens_#{version}_linux_arm64.tar.gz"
      sha256 "a9494c080edf28f033f9a98aea8a59ce9e5186b6789140790a4d319e98c473ec"
    end
  end

  # No zap stanza required
end
