# This file was generated by GoReleaser. DO NOT EDIT.
cask "tflens" do
  name "tflens"
  desc "tflens offers tiny utilities for terraform/opentofu/terragrunt codebases"
  homepage "https://github.com/dhth/tflens"
  version "0.1.0-alpha.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tflens"

  on_macos do
    on_intel do
      url "https://github.com/dhth/tflens/releases/download/v#{version}/tflens_#{version}_darwin_amd64.tar.gz"
      sha256 "2f723b6fc7fd8cfd3870186e81b0d5bea0ea38c0998a2caf1db72eb584d97faa"
    end
    on_arm do
      url "https://github.com/dhth/tflens/releases/download/v#{version}/tflens_#{version}_darwin_arm64.tar.gz"
      sha256 "342ea3059880b666ba7ab0ccbb90a23f2f90ec6d4823d1a61aab1cb17605757c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dhth/tflens/releases/download/v#{version}/tflens_#{version}_linux_amd64.tar.gz"
      sha256 "8f26cad9ed82c7126ac8138470d48ce84816750db4b6e956ae3b9d0b50c0b5c7"
    end
    on_arm do
      url "https://github.com/dhth/tflens/releases/download/v#{version}/tflens_#{version}_linux_arm64.tar.gz"
      sha256 "be4f5ce5aa6d123cf61a2e65c7db68932c9410bcee96b8ab26beb03bbb975742"
    end
  end

  # No zap stanza required
end
