# This file was generated by GoReleaser. DO NOT EDIT.
cask "tflens" do
  name "tflens"
  desc "tflens offers tiny utilities for terraform/opentofu/terragrunt codebases"
  homepage "https://github.com/dhth/tflens"
  version "0.1.0-alpha.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tflens"

  on_macos do
    on_intel do
      url "https://github.com/dhth/tflens/releases/download/v#{version}/tflens_#{version}_darwin_amd64.tar.gz"
      sha256 "3e1b3bcb300a2e0d8cf36fdb5c92a9eb4d4948c69c294f3ae35834524dc0bf59"
    end
    on_arm do
      url "https://github.com/dhth/tflens/releases/download/v#{version}/tflens_#{version}_darwin_arm64.tar.gz"
      sha256 "bb42f333ba88554044b64d5ab64544a03e6ecb191d5f66adc25cd25741159c94"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dhth/tflens/releases/download/v#{version}/tflens_#{version}_linux_amd64.tar.gz"
      sha256 "50ac81645c8c40d6e838a751b382b55f2734f14fb34a45512faa9600f79f61e4"
    end
    on_arm do
      url "https://github.com/dhth/tflens/releases/download/v#{version}/tflens_#{version}_linux_arm64.tar.gz"
      sha256 "f9f6cc4d27951ce4b0d8d88b3a3dae2aa927dff51ce15e21dd572e75fd7b8e78"
    end
  end

  # No zap stanza required
end
