# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Act3 < Formula
  desc "Glance at the last 3 runs of your Github Actions"
  homepage "https://github.com/dhth/act3"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dhth/act3/releases/download/v0.3.0/act3_0.3.0_darwin_amd64.tar.gz"
      sha256 "7315421a68213b99eac794a92be34390f0cb175a91d490085719c0b2f15a0432"

      def install
        bin.install "act3"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dhth/act3/releases/download/v0.3.0/act3_0.3.0_darwin_arm64.tar.gz"
      sha256 "f0318012d88bdd67b6ca5911a78b25e40ee66e80812f478d50bc067d810e134d"

      def install
        bin.install "act3"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dhth/act3/releases/download/v0.3.0/act3_0.3.0_linux_arm64.tar.gz"
      sha256 "9a926abbecbc007b9cb677e288e6acf80eabe802602ba4bbdb6676df92aa8385"

      def install
        bin.install "act3"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dhth/act3/releases/download/v0.3.0/act3_0.3.0_linux_amd64.tar.gz"
      sha256 "6ee8b3314ea6539c423aa5955f601326f67ce278190ace8034b4c4df2435f196"

      def install
        bin.install "act3"
      end
    end
  end
end
