# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cueitup < Formula
  desc "Inspect messages in an AWS SQS queue in a simple and deliberate manner"
  homepage "https://github.com/dhth/cueitup"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dhth/cueitup/releases/download/v0.2.1/cueitup_0.2.1_darwin_amd64.tar.gz"
      sha256 "a71e5973d59417115f355fe808577ded948952c5e65c0f06504642c9c79ec2f9"

      def install
        bin.install "cueitup"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dhth/cueitup/releases/download/v0.2.1/cueitup_0.2.1_darwin_arm64.tar.gz"
      sha256 "da592c2b1f5ac12d35eff415d0966cb74d1d0feed0a1ee5d910cc01c6e9cca54"

      def install
        bin.install "cueitup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dhth/cueitup/releases/download/v0.2.1/cueitup_0.2.1_linux_amd64.tar.gz"
      sha256 "8889f2a8b17c378af3948b0d6be803a430dedd54f8d512b2c68cabfdb4201b39"

      def install
        bin.install "cueitup"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dhth/cueitup/releases/download/v0.2.1/cueitup_0.2.1_linux_arm64.tar.gz"
      sha256 "ee47b64106f406fe1dcc6cfa6f5c34320a97bbeefe5b71b432ad15cc3496bb65"

      def install
        bin.install "cueitup"
      end
    end
  end
end
