# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cueitup < Formula
  desc "Inspect messages in an AWS SQS queue in a simple and deliberate manner"
  homepage "https://github.com/dhth/cueitup"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dhth/cueitup/releases/download/v0.2.2/cueitup_0.2.2_darwin_amd64.tar.gz"
      sha256 "5571de68240d7c5b9f53987a754a432e70c4d3ad9043dd4c6b22a82164f582c1"

      def install
        bin.install "cueitup"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dhth/cueitup/releases/download/v0.2.2/cueitup_0.2.2_darwin_arm64.tar.gz"
      sha256 "87a22573c74b125c52e719b7a358b561c1346b34dd4dccc2aa681a7d614b3c81"

      def install
        bin.install "cueitup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dhth/cueitup/releases/download/v0.2.2/cueitup_0.2.2_linux_amd64.tar.gz"
        sha256 "359089c6a20092ff466c76b8c5e8cacf18ad20503a7db817befbeed49e2b2e54"

        def install
          bin.install "cueitup"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dhth/cueitup/releases/download/v0.2.2/cueitup_0.2.2_linux_arm64.tar.gz"
        sha256 "b24bd59b51cc75c4d57d719379c8df5dc7d9245f0168a275a47173736439f582"

        def install
          bin.install "cueitup"
        end
      end
    end
  end
end
