# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cueitup < Formula
  desc "Inspect messages in an AWS SQS queue in a simple and deliberate manner"
  homepage "https://github.com/dhth/cueitup"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dhth/cueitup/releases/download/v1.0.0/cueitup_1.0.0_darwin_amd64.tar.gz"
      sha256 "00ab2283cfbfcf8f81c0f15b5abaf005ce464cee14de6c81b7ffb0dd3b258a1d"

      def install
        bin.install "cueitup"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dhth/cueitup/releases/download/v1.0.0/cueitup_1.0.0_darwin_arm64.tar.gz"
      sha256 "60ff841c169eda4b5eaab61e2dd93f3634de1d5abf4c461d546f7dead26756d3"

      def install
        bin.install "cueitup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dhth/cueitup/releases/download/v1.0.0/cueitup_1.0.0_linux_amd64.tar.gz"
        sha256 "e427e33fc6964b78cb070bdc88a6dc21469efc0957c923e556c3ffc0798cc15f"

        def install
          bin.install "cueitup"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dhth/cueitup/releases/download/v1.0.0/cueitup_1.0.0_linux_arm64.tar.gz"
        sha256 "25b6fd6aae5a58423540ed4140b5ec0f1ac6b5e96aa4930fd99d868ad142ce05"

        def install
          bin.install "cueitup"
        end
      end
    end
  end
end
