# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dstll < Formula
  desc "dstll gives you a high level overview of code constructs"
  homepage "https://github.com/dhth/dstll"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/dhth/dstll/releases/download/v0.1.0/dstll_0.1.0_darwin_amd64.tar.gz"
      sha256 "c5262eb6c44f50ac9f1342be108479555d94277693beb8f8599ef83168940e4f"

      def install
        bin.install "dstll"
      end
    end
    on_arm do
      url "https://github.com/dhth/dstll/releases/download/v0.1.0/dstll_0.1.0_darwin_arm64.tar.gz"
      sha256 "6224e2e90da58d546dbaf32722b9dd28e6808c4a6767b828616a3c8a73df0830"

      def install
        bin.install "dstll"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dhth/dstll/releases/download/v0.1.0/dstll_0.1.0_linux_amd64.tar.gz"
        sha256 "27056f43e2a88cc596d868079c9cbf7ae0de3e2dc6bbcfaaf5f8e14a7fbb0a10"

        def install
          bin.install "dstll"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dhth/dstll/releases/download/v0.1.0/dstll_0.1.0_linux_arm64.tar.gz"
        sha256 "14c1db416aac5158166e7621b69bb55038a1670fdfc906d17a90e44a7a92ee77"

        def install
          bin.install "dstll"
        end
      end
    end
  end
end
