# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dstll < Formula
  desc "dstll gives you a high level overview of code constructs"
  homepage "https://github.com/dhth/dstll"
  version "0.2.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/dhth/dstll/releases/download/v0.2.0/dstll_0.2.0_darwin_amd64.tar.gz"
      sha256 "94d7866075902733cd30cf7fd1e010577d20df261ee9fc11b13f2b3d22c0a759"

      def install
        bin.install "dstll"
      end
    end
    on_arm do
      url "https://github.com/dhth/dstll/releases/download/v0.2.0/dstll_0.2.0_darwin_arm64.tar.gz"
      sha256 "1b91f607db4a7eb4d152b73a74f223d4330e29702900f3a5729aa7fa8a93ff1d"

      def install
        bin.install "dstll"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dhth/dstll/releases/download/v0.2.0/dstll_0.2.0_linux_amd64.tar.gz"
        sha256 "23cfcc41158500a7d1e4bc5caf003501f7a675fb6cf29cf602d166875ffc8334"

        def install
          bin.install "dstll"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dhth/dstll/releases/download/v0.2.0/dstll_0.2.0_linux_arm64.tar.gz"
        sha256 "d94d6840ae291296854e1ac1f2d70bf6083ca48319cfdbd52b1ae594642f748b"

        def install
          bin.install "dstll"
        end
      end
    end
  end
end
