# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ecsv < Formula
  desc "Quickly check the versions of your systems running in ECS tasks across various environments"
  homepage "https://github.com/dhth/ecsv"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dhth/ecsv/releases/download/v0.1.0/ecsv_0.1.0_darwin_arm64.tar.gz"
      sha256 "b776f29a1c46f55052cff2b3dc84fcf3e6ecf43b37f368387f965901f992ef40"

      def install
        bin.install "ecsv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dhth/ecsv/releases/download/v0.1.0/ecsv_0.1.0_darwin_amd64.tar.gz"
      sha256 "845a6e8042ad9f1bb46d3b729e4162e06fead0aaee820299cb52f02df894932f"

      def install
        bin.install "ecsv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dhth/ecsv/releases/download/v0.1.0/ecsv_0.1.0_linux_arm64.tar.gz"
      sha256 "7d833b2f12bc48491e470a8ab3c3a523127c3b42d749190a579ce8b2f8c23cfb"

      def install
        bin.install "ecsv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dhth/ecsv/releases/download/v0.1.0/ecsv_0.1.0_linux_amd64.tar.gz"
      sha256 "343a750b47b60b8bb0dd75da7e7e14f27a1473656ee17b081328c89debe386c0"

      def install
        bin.install "ecsv"
      end
    end
  end
end
