# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ecsv < Formula
  desc "Quickly check the versions of your systems running in ECS tasks across various environments"
  homepage "https://github.com/dhth/ecsv"
  version "1.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dhth/ecsv/releases/download/v1.4.1/ecsv_1.4.1_darwin_amd64.tar.gz"
      sha256 "e5d8d72a4ff80e93c822d823eb7d0f04d397c2e20868e63fc5c17332f4da33ce"

      def install
        bin.install "ecsv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dhth/ecsv/releases/download/v1.4.1/ecsv_1.4.1_darwin_arm64.tar.gz"
      sha256 "bd718bb30bc45fa618aeadb80726d7c2cbffef3378378a999688c5c4cbbab841"

      def install
        bin.install "ecsv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dhth/ecsv/releases/download/v1.4.1/ecsv_1.4.1_linux_amd64.tar.gz"
        sha256 "c4aa93131423520956e61c55db6406caa2461b1b4a2251cbcbefd4673f969cff"

        def install
          bin.install "ecsv"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dhth/ecsv/releases/download/v1.4.1/ecsv_1.4.1_linux_arm64.tar.gz"
        sha256 "0ca385684ad59b379f174a643d84bdb3d83f370bb82df3a9ca6fb2c6c2788e95"

        def install
          bin.install "ecsv"
        end
      end
    end
  end
end
