# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ez < Formula
  desc "write stdin to stdout, but slowly"
  homepage "https://github.com/dhth/ez"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dhth/ez/releases/download/v0.1.1/ez_0.1.1_darwin_arm64.tar.gz"
      sha256 "e768fd2d01ed0d3c7dbc92f2e775f3571c759b4a2a21d69d9585a48eb92b2406"

      def install
        bin.install "ez"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dhth/ez/releases/download/v0.1.1/ez_0.1.1_darwin_amd64.tar.gz"
      sha256 "aa57c1c14812acf22203062f2316ba6f51ee1e8729e4138c1d6198456d348c2f"

      def install
        bin.install "ez"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dhth/ez/releases/download/v0.1.1/ez_0.1.1_linux_amd64.tar.gz"
      sha256 "1234cfa2210ba79a4cd6f791c1358d7568c8f2f4ffc7513e9cb59bb4a02053a6"

      def install
        bin.install "ez"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dhth/ez/releases/download/v0.1.1/ez_0.1.1_linux_arm64.tar.gz"
      sha256 "e2565b71ae95ce2ce26d482598f399ff641a97c58218ac010e6e3aeaadfef4d0"

      def install
        bin.install "ez"
      end
    end
  end
end
