# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gobrewtest < Formula
  desc "A completely useless binary; used for testing purposes"
  homepage "https://github.com/dhth/gobrewtest"
  version "0.2.5"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/dhth/gobrewtest/releases/download/v0.2.5/gobrewtest_0.2.5_darwin_amd64.tar.gz"
      sha256 "e7a0cf9e45de7a59fde5114c79496b8dd5117827901c215b0a48ac74d4d873d6"

      def install
        bin.install "gobrewtest"
      end
    end
    on_arm do
      url "https://github.com/dhth/gobrewtest/releases/download/v0.2.5/gobrewtest_0.2.5_darwin_arm64.tar.gz"
      sha256 "1179e8eedfa5246fc9aaf03c2cbdcaf9d0d55ebdd7aba018209779a84c8c380a"

      def install
        bin.install "gobrewtest"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dhth/gobrewtest/releases/download/v0.2.5/gobrewtest_0.2.5_linux_amd64.tar.gz"
        sha256 "e0066f241249e9242a3f2abddd9c26cbb3dc0a7f784a238e24d5f0e79a9d197a"

        def install
          bin.install "gobrewtest"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dhth/gobrewtest/releases/download/v0.2.5/gobrewtest_0.2.5_linux_arm64.tar.gz"
        sha256 "aba1a16e38e97bb3affc2bf4e805155581b50a05db6cd14c7c0e0bed28206aa7"

        def install
          bin.install "gobrewtest"
        end
      end
    end
  end
end
