# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gobrewtest < Formula
  desc "A completely useless binary; used for testing purposes"
  homepage "https://github.com/dhth/gobrewtest"
  version "0.2.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/dhth/gobrewtest/releases/download/v0.2.1/gobrewtest_0.2.1_darwin_amd64.tar.gz"
      sha256 "9c6f97187faebbba8d8c6a230f30d50fb6b79597b24a00c5fe3addda620d42ff"

      def install
        bin.install "gobrewtest"
      end
    end
    on_arm do
      url "https://github.com/dhth/gobrewtest/releases/download/v0.2.1/gobrewtest_0.2.1_darwin_arm64.tar.gz"
      sha256 "89714bd64b2d11fd4cb2b957ac1662f86704a8912881988068fbe49c2bbb2302"

      def install
        bin.install "gobrewtest"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dhth/gobrewtest/releases/download/v0.2.1/gobrewtest_0.2.1_linux_amd64.tar.gz"
        sha256 "d844fa16720f03c0e3515ef517b009b9ad760d80ea7245314ab13c669c77b68a"

        def install
          bin.install "gobrewtest"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dhth/gobrewtest/releases/download/v0.2.1/gobrewtest_0.2.1_linux_arm64.tar.gz"
        sha256 "033f6dfeef8c5d20f1a575f8970673c0356c743aa53940f26f49b9b36d3c83b7"

        def install
          bin.install "gobrewtest"
        end
      end
    end
  end
end
