# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoreleaserExampleRust < Formula
  desc "a sample project to test releasing rust binaries using goreleaser"
  homepage "https://github.com/dhth/goreleaser-example-rust"
  version "0.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dhth/goreleaser-example-rust/releases/download/v0.1.7/goreleaser-example-rust_0.1.7_darwin_arm64.tar.gz"
      sha256 "a3ff26687d8ccd27c32cff082f7a9a924cfa015faca82369d87729fa73d6166c"

      def install
        bin.install "goreleaser-example-rust"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dhth/goreleaser-example-rust/releases/download/v0.1.7/goreleaser-example-rust_0.1.7_linux_arm64.tar.gz"
        sha256 "cf2e0fb835715a7f77fd470c2831c13d4ed306472e15cd6eb8f7546672349206"

        def install
          bin.install "goreleaser-example-rust"
        end
      end
    end
  end
end
