# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hours < Formula
  desc "A no-frills time tracking toolkit for the command line"
  homepage "https://github.com/dhth/hours"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dhth/hours/releases/download/v0.5.0/hours_0.5.0_darwin_amd64.tar.gz"
      sha256 "1bed2bfc79d7e5a5f30f994d377e598ddcfbdb81deff49f7c69455d68144f1aa"

      def install
        bin.install "hours"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dhth/hours/releases/download/v0.5.0/hours_0.5.0_darwin_arm64.tar.gz"
      sha256 "41317f52242f74fae8bfcb18b9ae1ae44b8cd0918bfbf0283c174bffad3132d2"

      def install
        bin.install "hours"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dhth/hours/releases/download/v0.5.0/hours_0.5.0_linux_amd64.tar.gz"
        sha256 "9bf016633fdacbde65e61266fa5f9e919a014115b8149202027fbf6f61634aea"

        def install
          bin.install "hours"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dhth/hours/releases/download/v0.5.0/hours_0.5.0_linux_arm64.tar.gz"
        sha256 "e24c3a9cc67eb45bdd6533016e974f3325c12cb763c00cdfa8e88b156efd43d7"

        def install
          bin.install "hours"
        end
      end
    end
  end
end
