# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Inc < Formula
  desc "get the next semver for your repo from git tags"
  homepage "https://github.com/dhth/inc"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dhth/inc/releases/download/v0.1.0/inc_0.1.0_darwin_arm64.tar.gz"
      sha256 "d75f88f5a83ee3787be70d916bfc95b1b443d4e777911c161a9f82f964f47491"

      def install
        bin.install "inc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dhth/inc/releases/download/v0.1.0/inc_0.1.0_darwin_amd64.tar.gz"
      sha256 "5b832d465fd6ec7f4c66de26b5fd5c2a38720b6911599768a6730a7141dda062"

      def install
        bin.install "inc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dhth/inc/releases/download/v0.1.0/inc_0.1.0_linux_arm64.tar.gz"
      sha256 "3e2ebb58569347edc2ae48421dbc2a14cf9979ae37302b98bbd4b5911c9e5573"

      def install
        bin.install "inc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dhth/inc/releases/download/v0.1.0/inc_0.1.0_linux_amd64.tar.gz"
      sha256 "1f3b515c16f86989a44c492cb7bf77c68371a346adb15fcbdc5899d043ccc899"

      def install
        bin.install "inc"
      end
    end
  end
end
