# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mult < Formula
  desc "Run a command multiple times and glance at the outputs"
  homepage "https://github.com/dhth/mult"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dhth/mult/releases/download/v0.3.0/mult_0.3.0_darwin_amd64.tar.gz"
      sha256 "0252921cd23e68c1015e941c4668a45b61755ce3b15c14c512a7fbbdcdcbaa53"

      def install
        bin.install "mult"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dhth/mult/releases/download/v0.3.0/mult_0.3.0_darwin_arm64.tar.gz"
      sha256 "863dd798ba10073843cd9020c44522f2e69648870e2cc2b32ee961b5b99430bd"

      def install
        bin.install "mult"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/dhth/mult/releases/download/v0.3.0/mult_0.3.0_linux_amd64.tar.gz"
      sha256 "cf2fd7e42ee748d2573c50781cf4f8334809f6d951589d2851dd09d987b3d3ac"
      def install
        bin.install "mult"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/dhth/mult/releases/download/v0.3.0/mult_0.3.0_linux_arm64.tar.gz"
      sha256 "f349c122fa7ae8dbfad973c18d15a4baa4fb05aee7f23490ff6ff8e3bb02ef2c"
      def install
        bin.install "mult"
      end
    end
  end
end
