# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mult < Formula
  desc "Run a command multiple times and glance at the outputs"
  homepage "https://github.com/dhth/mult"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/dhth/mult/releases/download/v0.1.0/mult_0.1.0_darwin_amd64.tar.gz"
      sha256 "7431c9f298f22b659f0ec51132c5261aab8ddb61374a166f35d49134661f22d7"

      def install
        bin.install "mult"
      end
    end
    on_arm do
      url "https://github.com/dhth/mult/releases/download/v0.1.0/mult_0.1.0_darwin_arm64.tar.gz"
      sha256 "712fc8941535c2cd94b7cafa9f221eb82ceee0f2e5a0548eac7077e5fcf1d2a0"

      def install
        bin.install "mult"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dhth/mult/releases/download/v0.1.0/mult_0.1.0_linux_amd64.tar.gz"
        sha256 "5debb87254a927147d11d2720a54dc5e33fe372a6cf42907a07aa86a29c4ec7b"

        def install
          bin.install "mult"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dhth/mult/releases/download/v0.1.0/mult_0.1.0_linux_arm64.tar.gz"
        sha256 "96987c9927c8a9cd4ccb50f775d93c626d4d7e47b9b15a6f909a8c0ac2d0d1be"

        def install
          bin.install "mult"
        end
      end
    end
  end
end
