# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Omm < Formula
  desc "omm is a keyboard-driven task manager for the command line"
  homepage "https://github.com/dhth/omm"
  version "0.4.3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/dhth/omm/releases/download/v0.4.3/omm_0.4.3_darwin_amd64.tar.gz"
      sha256 "83994c13f4762bd09c6ca0cd45e9d17651f11c6180b5dd15fdcc850b12086977"

      def install
        bin.install "omm"
      end
    end
    on_arm do
      url "https://github.com/dhth/omm/releases/download/v0.4.3/omm_0.4.3_darwin_arm64.tar.gz"
      sha256 "6a2ce79dfbc168167e0e7e721b51f7d2875e167e2eacd91a0c28e2defbf80498"

      def install
        bin.install "omm"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dhth/omm/releases/download/v0.4.3/omm_0.4.3_linux_amd64.tar.gz"
        sha256 "a168e2852b8b5c5fa7c118731cd2b8074ac23f99c399f865cc56f896a2798a04"

        def install
          bin.install "omm"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dhth/omm/releases/download/v0.4.3/omm_0.4.3_linux_arm64.tar.gz"
        sha256 "73e07978ab9142c5c49d41a7bec280690880291d28164009b71b874d5ff94d37"

        def install
          bin.install "omm"
        end
      end
    end
  end
end
