# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Omm < Formula
  desc "omm is a keyboard-driven task manager for the command line"
  homepage "https://github.com/dhth/omm"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dhth/omm/releases/download/v0.7.0/omm_0.7.0_darwin_amd64.tar.gz"
      sha256 "6b925a5b9e8fa1eb7ceceded9c404e53affbb302cfc66b40dad2402203e9baa3"

      define_method(:install) do
        bin.install "omm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dhth/omm/releases/download/v0.7.0/omm_0.7.0_darwin_arm64.tar.gz"
      sha256 "1cf6eaf5dc8c0b09de7c042ba38e12284b66068dc0e28740d436f492247157c1"

      define_method(:install) do
        bin.install "omm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dhth/omm/releases/download/v0.7.0/omm_0.7.0_linux_amd64.tar.gz"
      sha256 "95f6e51ecff1bddc69e7813f5117e441b3921b8ed051922a8de020da8b4d35f0"
      define_method(:install) do
        bin.install "omm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dhth/omm/releases/download/v0.7.0/omm_0.7.0_linux_arm64.tar.gz"
      sha256 "377296286d6cb771fb402dfff9295ed28bf9b1d5b945881e40564f68ab133e9a"
      define_method(:install) do
        bin.install "omm"
      end
    end
  end
end
