# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Outtasync < Formula
  desc "Quickly identify CloudFormation stacks that have gone out of sync with their counterpart stack files"
  homepage "https://github.com/dhth/outtasync"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dhth/outtasync/releases/download/v0.1.4/outtasync_0.1.4_darwin_amd64.tar.gz"
      sha256 "1336437828a43364a94b73a2cbd0369b801dbfd6d4981aab297521d5d89d7978"

      def install
        bin.install "outtasync"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dhth/outtasync/releases/download/v0.1.4/outtasync_0.1.4_darwin_arm64.tar.gz"
      sha256 "a83dc94967fe720a3fee3d9b45126b388c1a7006b71f32eabc1a762d88bdd916"

      def install
        bin.install "outtasync"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dhth/outtasync/releases/download/v0.1.4/outtasync_0.1.4_linux_arm64.tar.gz"
      sha256 "0315157a5d6c5e7dab75bb8cc705c8984b18a31af7b708e5371bcaced0eb02fc"

      def install
        bin.install "outtasync"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dhth/outtasync/releases/download/v0.1.4/outtasync_0.1.4_linux_amd64.tar.gz"
      sha256 "6205557cbf8740bbd8cf900f7b80eca15700fdbc2c0a9507961ccd148307f062"

      def install
        bin.install "outtasync"
      end
    end
  end
end
