# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Punchout < Formula
  desc "punchout takes the suck out of logging time on JIRA"
  homepage "https://github.com/dhth/punchout"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dhth/punchout/releases/download/v0.1.0/punchout_0.1.0_darwin_amd64.tar.gz"
      sha256 "9d894bff3eccc271661cb9145088f7563e193112f7e3285463e2a88f5d571ec3"

      def install
        bin.install "punchout"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dhth/punchout/releases/download/v0.1.0/punchout_0.1.0_darwin_arm64.tar.gz"
      sha256 "9cedfe694895bd4b8ebcf4439fd605d25ccd4c527df0eb49001d4ba2b05ff4e2"

      def install
        bin.install "punchout"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dhth/punchout/releases/download/v0.1.0/punchout_0.1.0_linux_amd64.tar.gz"
      sha256 "0d610b968949379e795cec764e48fdea9c98d4083ec3032c599d0bf0e8f4fc87"

      def install
        bin.install "punchout"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dhth/punchout/releases/download/v0.1.0/punchout_0.1.0_linux_arm64.tar.gz"
      sha256 "7d582c4791cdbee1d05e63831a99ec5136d3376da5b30c1ca3bf325507928c25"

      def install
        bin.install "punchout"
      end
    end
  end
end
