# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Punchout < Formula
  desc "punchout takes the suck out of logging time on JIRA"
  homepage "https://github.com/dhth/punchout"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dhth/punchout/releases/download/v0.3.0/punchout_0.3.0_darwin_amd64.tar.gz"
      sha256 "9f742ca4c79b8f34a66c8b22c366b6fa2c140ff0f0d88286ed9be4d8132b24dd"

      def install
        bin.install "punchout"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dhth/punchout/releases/download/v0.3.0/punchout_0.3.0_darwin_arm64.tar.gz"
      sha256 "3fa936529dacc28eb1a938093f3467de1f1305aa6e10b152186c6ef07081cb0b"

      def install
        bin.install "punchout"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dhth/punchout/releases/download/v0.3.0/punchout_0.3.0_linux_amd64.tar.gz"
      sha256 "dfc4b196d9478c78c5192fe83831441927390965c4eafc0b9a1e369dcaee1ffb"

      def install
        bin.install "punchout"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dhth/punchout/releases/download/v0.3.0/punchout_0.3.0_linux_arm64.tar.gz"
      sha256 "677f2ca908e41cb4b0e0536e3f7ccd8b0300027dceb188adb09f1c69f4aed74b"

      def install
        bin.install "punchout"
      end
    end
  end
end
