# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Schemas < Formula
  desc "Inspect postgres schemas in the terminal"
  homepage "https://github.com/dhth/schemas"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dhth/schemas/releases/download/v0.1.1/schemas_0.1.1_darwin_arm64.tar.gz"
      sha256 "a84a23ee027e0d0437984d40f9204a7da4f5b5f3f8a71fd4fc3f8ec65a96f754"

      def install
        bin.install "schemas"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dhth/schemas/releases/download/v0.1.1/schemas_0.1.1_darwin_amd64.tar.gz"
      sha256 "74b8c63fb0f8637fef4e22eeed121d13d9f98cccb1b2e1c37a15c12ba88f1dba"

      def install
        bin.install "schemas"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dhth/schemas/releases/download/v0.1.1/schemas_0.1.1_linux_arm64.tar.gz"
      sha256 "3eb99daaff80b7db359a4b1e8035484bae4e05764f4321c0b3b1072ec4c140ce"

      def install
        bin.install "schemas"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dhth/schemas/releases/download/v0.1.1/schemas_0.1.1_linux_amd64.tar.gz"
      sha256 "c038c038ef5bef0d2ce1e0790dd42298179b8797734bea8f834e16c3c76f85c0"

      def install
        bin.install "schemas"
      end
    end
  end
end
