# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shfl < Formula
  desc "shfl lets you rearrange lines in a file with simple keymaps"
  homepage "https://github.com/dhth/shfl"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dhth/shfl/releases/download/v0.1.0/shfl_0.1.0_darwin_arm64.tar.gz"
      sha256 "a2c93a23b843f1e3b8a66cd3f34653d62fdee40858036a6af0fe2491957b4a1b"

      def install
        bin.install "shfl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dhth/shfl/releases/download/v0.1.0/shfl_0.1.0_linux_arm64.tar.gz"
        sha256 "56e564d4975469b08e627d530701e1455cd0f6188205a885e4767ba3f6c1d459"

        def install
          bin.install "shfl"
        end
      end
    end
  end
end
